# Generated by Django 5.1 on 2024-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(max_length=50, verbose_name='Mot de passe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé à')),
            ],
        ),
    ]
