# Generated by Django 5.1 on 2024-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de famille')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Genre')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('level', models.CharField(max_length=50, verbose_name='Niveau')),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'inscription")),
            ],
        ),
    ]
