# Generated by Django 5.1 on 2024-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Genre'),
        ),
    ]
