# Generated by Django 5.1 on 2024-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('subject', models.CharField(max_length=50, verbose_name='Matière')),
                ('vacant', models.CharField(max_length=50, verbose_name='Vacant')),
                ('next_meeting_subject', models.CharField(max_length=50, verbose_name='Sujet de la prochaine réunion')),
            ],
        ),
    ]
